name: Compile LaTeX
on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=latex-out"

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-latex-${{ github.ref_name }}
          path: latex-out/main.pdf
